export const allProducts = [
  {
    id: "1",
    file: "/products/product_1.png",
    name: "Ivory Black Abstract Wave Coord",
    nameHi: "आइवरी ब्लैक एब्स्ट्रैक्ट वेव को-ऑर्ड",
    category: "Coord Sets",
    price: 999,
    originalPrice: 1998,
    vibe: "Statement · Urban · Fashion-Forward",
    availableSizes: ["S", "M", "L", "XL", "XXL"],
    description: "A bold and contemporary ivory cotton flax coord featuring a large-scale abstract wave and geometric shape print in black and graphite. The maxi-length mandarin-collar shirt with full front button opening and wide-leg matching trousers give an editorial, fashion-forward feel — designed in India.",
    descriptionHi: "आइवरी कॉटन फ्लैक्स को-ऑर्ड में लार्ज-स्केल एब्स्ट्रैक्ट वेव और जियोमेट्रिक शेप प्रिंट। मैक्सी-लेंथ मंदारिन कॉलर शर्ट और वाइड-लेग ट्राउज़र्स के साथ।",
    details: "Shell: 100% cotton flax. Off-white base with bold large-scale abstract wave and geometric shape print in black, graphite and grey. Maxi-length mandarin collar shirt with full-length front button opening and roll-up sleeve tab. Matching wide-leg trousers with the same graphic print. Machine washable on cold.",
    features: ["100% Cotton Flax", "Bold abstract geometric print", "Maxi-length mandarin collar shirt", "Full front button opening", "Matching wide-leg trousers", "Roll-up sleeve tabs"],
  },
  {
    id: "2",
    file: "/products/product_2.png",
    name: "Charcoal Terracotta Floral 3-Piece Suit",
    nameHi: "चारकोल टेराकोटा फ्लोरल 3-पीस सूट",
    category: "3-Piece Suits",
    price: 1099,
    originalPrice: 2198,
    vibe: "Heritage · Festive · Traditional",
    availableSizes: ["S", "M", "L", "XL", "XXL"],
    description: "A richly detailed dark charcoal cotton suit with an all-over terracotta and rust floral sprig print. The decorative Kutchi-style yoke panel with signature red tassels anchors the look beautifully.",
    descriptionHi: "डार्क चारकोल कॉटन सूट में टेराकोटा फ्लोरल प्रिंट। कच्छी-स्टाइल योक पैनल, रेड टैसल और जियोमेट्रिक बॉर्डर दुपट्टा के साथ।",
    details: "Shell: 100% cotton. Deep charcoal kurta with all-over terracotta and rust floral sprig print. Decorative Kutchi-style yoke panel with geometric embroidery and signature red tassels. Complete 3-piece set. Gentle hand wash recommended.",
    features: ["100% Cotton", "Terracotta floral sprig print", "Kutchi-style embroidered yoke", "Red tassel neckline detail", "Geometric border dupatta", "Complete 3-piece set"],
  },
  {
    id: "3",
    file: "/products/product_3.png",
    name: "Mustard Kutchi Mirror-Work Kurta Set",
    nameHi: "मस्टर्ड कच्छी मिरर-वर्क कुर्ता सेट",
    category: "Kurta Sets",
    price: 999,
    originalPrice: 1998,
    vibe: "Office · Festive · Heritage",
    availableSizes: ["S", "L", "XL", "XXL"],
    description: "A vibrant deep mustard cotton kurta set featuring three hand-placed Kutchi mirror-work medallions on the front. The V-neck with embroidered geometric trim and tassel pendant makes this a statement piece.",
    descriptionHi: "डीप मस्टर्ड कॉटन कुर्ता में कच्छी मिरर-वर्क मेडलियन। एम्ब्रॉयडर्ड V-नेक, टैसल पेंडेंट और मैचिंग वाइड-लेग पलाज़ो के साथ।",
    details: "Shell: 100% cotton. Deep mustard kurta with V-neckline featuring hand-embroidered geometric yoke trim and a hanging tassel pendant. Three Kutchi mirror-work medallion appliqués. Gentle hand wash recommended.",
    features: ["100% Cotton", "Kutchi mirror-work medallions", "Embroidered geometric V-neck", "Tassel pendant detail", "Three-quarter embroidered cuffs", "Matching wide-leg palazzo trousers"],
  },
  {
    id: "4",
    file: "/products/product_4.png",
    name: "Ivory Pink Climbing Rose 3-Piece Suit",
    nameHi: "आइवरी पिंक क्लाइम्बिंग रोज़ 3-पीस सूट",
    category: "3-Piece Suits",
    price: 1099,
    originalPrice: 2198,
    vibe: "Festive · Garden Party · Traditional",
    availableSizes: ["S", "M", "XL", "XXL"],
    description: "A romantic ivory cotton suit with a delicate climbing rose and floral vine print in soft pinks and sage green. The V-neck with lace trim adds timeless feminine grace.",
    descriptionHi: "आइवरी कॉटन सूट में डेलिकेट क्लाइम्बिंग रोज़ और फ्लोरल वाइन प्रिंट। लेस ट्रिम V-नेक और ब्लश पिंक मुगल-मोटिफ दुपट्टा के साथ।",
    details: "Shell: 100% cotton. Ivory kurta with all-over climbing floral vine print in blush pink and sage green. V-neckline with delicate lace trim. Complete 3-piece set. Gentle hand wash recommended.",
    features: ["100% Cotton", "Climbing rose floral vine print", "Lace trim V-neckline", "Pin-tuck yoke panel", "Blush dupatta with ornate Mughal border", "Complete 3-piece set"],
  },
  {
    id: "5",
    file: "/products/product_5.png",
    name: "Teal Floral Embroidered Kurta Set",
    nameHi: "टील फ्लोरल एम्ब्रॉयडर्ड कुर्ता सेट",
    category: "Kurta Sets",
    price: 999,
    originalPrice: 1998,
    vibe: "Office · Premium · Artisan",
    availableSizes: ["M"],
    description: "A stunning teal blue cotton kurta with flowing cream thread floral embroidery across the yoke, hemline border and sleeves. The distinctive split-cuff sleeves with pearl buttons and tassel ties are a design detail you will not find on the high street.",
    descriptionHi: "टील ब्लू कॉटन कुर्ता में क्रीम थ्रेड फ्लोरल एम्ब्रॉयडरी। स्प्लिट कफ, पर्ल बटन और टैसल टाई के साथ।",
    details: "Shell: 100% cotton. Solid teal blue kurta with all-over cream thread floral embroidery. Distinctive split-cuff sleeve with pearl button and tassel tie. Gentle hand wash only.",
    features: ["100% Cotton", "Hand cream thread floral embroidery", "Split-cuff with pearl button", "Tassel tie sleeve detail", "Scallop embroidered hemline", "Wide-leg teal palazzo trousers"],
  },
  {
    id: "6",
    file: "/products/product_6.png",
    name: "Teal Ajrakh Geometric 3-Piece Suit",
    nameHi: "टील अजरख जियोमेट्रिक 3-पीस सूट",
    category: "3-Piece Suits",
    price: 1099,
    originalPrice: 2198,
    vibe: "Heritage · Festive · Collector's Piece",
    availableSizes: ["S", "L", "XL", "XXL"],
    description: "A richly detailed teal cotton suit with Ajrakh-inspired geometric block print in deep red and ochre — rooted in one of India's oldest textile traditions.",
    descriptionHi: "टील कॉटन सूट में अजरख-इंस्पायर्ड जियोमेट्रिक ब्लॉक प्रिंट। कच्छी योक पैनल, रेड टैसल और पैचवर्क अजरख दुपट्टा।",
    details: "Shell: 100% cotton. Teal ground with dense Ajrakh geometric print in deep red, ochre and cream. Patchwork-style dupatta — each piece is entirely unique. Gentle hand wash only.",
    features: ["100% Cotton", "Ajrakh geometric block print", "Decorative Ajrakh yoke panel", "Red tassel detail", "Patchwork Ajrakh dupatta — each unique", "Kutch heritage craft"],
  },
  {
    id: "7",
    file: "/products/product_7.png",
    name: "Amber Leaf Print Button Coord",
    nameHi: "एम्बर लीफ प्रिंट बटन को-ऑर्ड",
    category: "Coord Sets",
    price: 999,
    originalPrice: 1998,
    vibe: "Casual · College · Artistic",
    availableSizes: ["S", "M", "L", "XL", "XXL"],
    description: "A warm amber and ivory cotton coord with an abstract botanical leaf and foliage print. The longline mandarin-collar shirt with full front button opening and wide-leg palazzo trousers make this an effortless all-day outfit.",
    descriptionHi: "वार्म एम्बर और आइवरी कॉटन को-ऑर्ड में एब्स्ट्रैक्ट बॉटेनिकल लीफ प्रिंट। मंदारिन कॉलर शर्ट और वाइड-लेग पलाज़ो के साथ।",
    details: "Shell: 100% cotton. Warm amber orange and cream abstract leaf print. Longline mandarin collar shirt with roll-up sleeve tabs. Machine washable.",
    features: ["100% Cotton", "Abstract botanical leaf print", "Longline mandarin collar shirt", "Full front button placket", "Wide-leg palazzo trousers", "Roll-up sleeve tabs"],
  },
  {
    id: "8",
    file: "/products/product_8.jpeg",
    name: "Rust Geometric Appliqué Kurta Set",
    nameHi: "रस्ट जियोमेट्रिक अप्लिक कुर्ता सेट",
    category: "Kurta Sets",
    price: 999,
    originalPrice: 1998,
    vibe: "Office · Everyday · Artisan",
    availableSizes: ["S", "M", "L", "XL", "XXL"],
    description: "A warm terracotta rust cotton kurta with three placed geometric appliqué medallions featuring bandhani-inspired dot work and cream thread stitching.",
    descriptionHi: "टेराकोटा रस्ट कॉटन कुर्ता में जियोमेट्रिक अप्लिक मेडलियन और बंधानी-इंस्पायर्ड डॉट वर्क।",
    details: "Shell: 100% cotton 60-60. Solid terracotta rust kurta with geometric appliqué medallions. Two side pockets. Kurti length 44 inches. Machine washable on cold.",
    features: ["100% Cotton 60-60", "Geometric appliqué medallions", "Bandhani-inspired dot work", "Embroidered V-neck with tassel", "Two side pockets", "Matching wide-leg rust trousers"],
  },
  {
    id: "9",
    file: "/products/product_9.png",
    name: "Blush Tulip Sleeveless Coord",
    nameHi: "ब्लश ट्यूलिप स्लीवलेस को-ऑर्ड",
    category: "Coord Sets",
    price: 799,
    originalPrice: 1598,
    vibe: "Summer · Casual · Garden",
    availableSizes: ["S", "M", "L", "XL", "XXL"],
    description: "A breezy blush pink cotton coord covered in a watercolour tulip, peach bloom and green leaf print. The sleeveless notched-collar shirt with patch pockets and relaxed trousers make this the easiest summer outfit.",
    descriptionHi: "ब्लश पिंक कॉटन को-ऑर्ड में वॉटरकलर ट्यूलिप और पीच ब्लूम प्रिंट। स्लीवलेस नॉच्ड कॉलर शर्ट और स्ट्रेट-लेग ट्राउज़र्स के साथ।",
    details: "Shell: 100% cotton. Soft blush pink with watercolour tulip print. Sleeveless notched-collar shirt with two patch pockets. Machine washable on cold.",
    features: ["100% Cotton", "Watercolour tulip & bloom print", "Sleeveless notched collar shirt", "Patch pockets on shirt", "Elasticated waist trousers", "Machine washable"],
  },
  {
    id: "10",
    file: "/products/product_10.png",
    name: "Black Paisley Block Print Coord",
    nameHi: "ब्लैक पेस्ले ब्लॉक प्रिंट को-ऑर्ड",
    category: "Coord Sets",
    price: 999,
    originalPrice: 1998,
    vibe: "Office · Evening · Statement",
    availableSizes: ["S", "M", "L", "XL", "XXL"],
    description: "A bold and graphic black cotton coord with striking cream Mughal-inspired paisley block print arranged in a large diamond grid. Minimal effort, maximum presence.",
    descriptionHi: "ब्लैक कॉटन को-ऑर्ड में क्रीम मुगल-इंस्पायर्ड पेस्ले ब्लॉक प्रिंट। लॉन्गलाइन मंदारिन कॉलर कुर्ता और वाइड-लेग पलाज़ो के साथ।",
    details: "Shell: 100% cotton. Black base with bold cream paisley in diamond lattice — block printed by hand. Deep side slits. Side pockets. Machine washable.",
    features: ["100% Cotton", "Hand block printed paisley", "Mughal diamond grid pattern", "Mandarin collar with roll-up sleeves", "Wide-leg palazzo trousers", "Deep side slits + side pockets"],
  },
];